CREATE DATABASE StudentLibManagement;
USE StudentLibManagement;

CREATE TABLE STUDENT(
	ROLL VARCHAR(6) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    DEPARTMENT VARCHAR(20) NOT NULL,
    AGE INT
);

CREATE TABLE BOOK(
	BOOK_ID VARCHAR(6) PRIMARY KEY,
    BOOK_NAME VARCHAR(50) NOT NULL,
    BOOK_GEN VARCHAR(20) 
);

CREATE TABLE LIBRANIAN(
	LIB_ID VARCHAR(6) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);
 
 
 
CREATE TABLE BRROW (
	BRROW_STUDENT_ROLL VARCHAR(6) ,
    BRROW_BOOK_ID VARCHAR(6),
    BRROW_DATE DATE,
    RETURN_DATE DATE,
    
    PRIMARY KEY (BRROW_STUDENT_ROLL, BRROW_BOOK_ID)
);

CREATE TABLE PERMITION(
	PER_LIB_ID VARCHAR(6),
    PER_BOOK_ID VARCHAR(6),
    
    PRIMARY KEY(PER_LIB_ID, PER_BOOK_ID)
)